# ------------------------------------------------------------------------------------------------------------ #
# Mandatorty variables - DO NOT LEAVE ANYTHING BLANK #
dp_vault_pgdb_password: "Qwerty12345"                  # postgres password for analytics db
dp_vault_pgdb_admin_password: "Qwerty12345"            # postgres password for admin
dp_vault_druid_postgress_pass: "Qwerty12345"           # postgres password for druid db

# Azure storage account credentials - Note if you are using a single account, you can set the same key for the belows
sunbird_management_storage_account_key: "0zLIRMZwAD8BABxq7OkG+51zORjFowrlrI6IC1NR4poKZvfKBLmE59fNxRoHnBTbG6HbWKcp9G+zp4nMDJ9VeA=="
sunbird_artifact_storage_account_key: "0zLIRMZwAD8BABxq7OkG+51zORjFowrlrI6IC1NR4poKZvfKBLmE59fNxRoHnBTbG6HbWKcp9G+zp4nMDJ9VeA=="
sunbird_private_storage_account_key: "0zLIRMZwAD8BABxq7OkG+51zORjFowrlrI6IC1NR4poKZvfKBLmE59fNxRoHnBTbG6HbWKcp9G+zp4nMDJ9VeA=="
sunbird_public_storage_account_key: "0zLIRMZwAD8BABxq7OkG+51zORjFowrlrI6IC1NR4poKZvfKBLmE59fNxRoHnBTbG6HbWKcp9G+zp4nMDJ9VeA=="
sunbird_druid_storage_account_key: "0zLIRMZwAD8BABxq7OkG+51zORjFowrlrI6IC1NR4poKZvfKBLmE59fNxRoHnBTbG6HbWKcp9G+zp4nMDJ9VeA=="
sunbird_artifact_storage_account_sas: "se=2032-05-11T12%3A05%3A12Z&sp=rwdlacup&spr=https&sv=2021-04-10&ss=tfqb&srt=soc&sig=iWo2KHOtpSXUm/2ZZRbjyeuMYiulBrtPGppKEeP0xEI%3D"           # this must be the sas token from Core directory that your generated

core_vault_docker_registry_url: "https://index.docker.io/v1"                 # for docker hub use https://index.docker.io/v1
core_vault_docker_registry_user: "saivignesh@bassure.com"
core_vault_docker_registry_password: "SAIvikki23@"

sunbird_api_auth_token:              # copy value form variable core_vault_sunbird_api_auth_token from core/secrets.yml
core_vault_sunbird_encryption_key: "change.sunbird.encryption.key"   # copy value from variable core_vault_sunbird_encryption_key from core secrets.yml

# ------------------------------------------------------------------------------------------------------------ #
# Optional variables - Can be left blank if you dont plan to use the intended features
dp_vault_data_exhaust_token:      # slack api token

# ------------------------------------------------------------------------------------------------------------ #
# Sensible defaults which you need not change - But if you would like to change, you are free to do so
dp_vault_artifacts_container: artifacts
